sonata_doctrine_orm_admin:
    templates:
        form:
            - 'SonataDoctrineORMAdminBundle:Form:form_admin_fields.html.twig'
            - '@SonataDoctrineORMAdmin/Form/custom_form_admin_fields.html.twig'