sonata_admin:
    title: ' '
    title_logo: '/build/images/CGJ-logo-2019-v2.svg'
    security:
        handler: sonata.admin.security.handler.role
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
        groups:
            'Registration':
            'Location':
            'Job Titles':
            'Job Announcements':
              items:
                - App\Admin\JobAnnouncementAdmin
                - App\Admin\ViewAdmin
                - App\Admin\AlertedJobAnnouncementAdmin
                - App\Admin\JobAnnouncementImpressionAdmin
            'City Links':
            'Subscriptions':
            'Importers':
            'Lookups':
            'Users':
            'News':
    show_mosaic_button:   false
    search: false
    options:
        html5_validate: false
    persist_filters: true
    assets:
        extra_stylesheets:
          - build/css/style.css
          - bundles/sonataformatter/markitup/skins/sonata/style.css
          - bundles/sonataformatter/markitup/sets/markdown/style.css
          - bundles/sonataformatter/markitup/sets/html/style.css
          - bundles/sonataformatter/markitup/sets/textile/style.css
        extra_javascripts:
          - build/admin.js
          - bundles/fosckeditor/ckeditor.js
          - bundles/sonataformatter/vendor/markitup-markitup/markitup/jquery.markitup.js
          - bundles/sonataformatter/markitup/sets/markdown/set.js
          - bundles/sonataformatter/markitup/sets/html/set.js
          - bundles/sonataformatter/markitup/sets/textile/set.js
          - js/cgj.js
#          - bundles/pixsortablebehavior/js/jquery-ui.min.js
#          - bundles/pixsortablebehavior/js/init.js
