monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]
#        mail:
#            type: fingers_crossed
#            # 500 errors are logged at the critical level
#            # action_level: critical
#            # to also log 400 level errors (but not 404's):
#            action_level: error
#            excluded_404s:
#                - ^/admin/*
#            handler: deduplicated
#        deduplicated:
#            type:    deduplication
#            handler: swift
#        swift:
#            type:       swift_mailer
#            from_email: 'error@citygovjobs.com'
#            to_email:   'tnguyen@endertech.com'
#            subject:    'PRODUCTION Error Occurred! %%message%%'
#            level:      debug
#            formatter:  monolog.formatter.html
#            content_type: text/html
        console:
            type:   console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
